/* ============================================================
   Zamborin · Karrots · world 1, the woods

   GENERATED by build-levels.mjs. Do not hand-edit: every par here is the
   length of the shortest solution a complete unpruned breadth-first search of
   the level's reachable positions could find, and editing one by hand would
   turn the three-carrot rating into a number nobody can trust.

   A level is six rows. '.' is a hole, '#' an immovable brick, 'B' the bunny,
   'F' the fox and 'C' the carrot, each of those three standing in a hole. A
   letter is one domino and appears exactly twice, on two adjacent cells.
   `carrotAt` puts the carrot under a tile instead, which §4.2 allows: the
   goal square is not reserved.
   ============================================================ */
(function (root, factory) {
  var api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.KarrotsLevels = api;
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  var LEVELS = [
    { id: 1, par: 4,
      rows: ['aabdd.eeg', 'hhbii.jjg', 'Ckkllm..n', 'o..p.mqqn', 'o.Bprrss.', 'Ftt.uu.vv'],
      // the first slide that opens the way to the carrot is the one that opens it to him too.
      // par 4, 2 with the fox rule off. 94 positions on the
      // way to the answer where one move loses and another does not, out of 358
      // searched. The first losing slide of any kind is 0 moves in.
    },
    { id: 2, par: 5,
      rows: ['.aabbddee', 'gg.hhiijj', 'kll.mmnn.', 'kBooppq..', 'rssFt.quu', 'r..Ct.vv.'],
      // a tighter board and the same trap one square along.
      // par 5, 1 with the fox rule off. 238 positions on the
      // way to the answer where one move loses and another does not, out of 693
      // searched. The first losing slide of any kind is 0 moves in.
    },
    { id: 3, par: 7,
      rows: ['..aabb.dd', 'e.ggh..ii', 'ejkkhl.mm', 'CjBnnl.oo', '.Fpp..qqr', 'ssttuuvvr'],
      // his corridor runs across the route; watch which end of it he is at.
      // par 7, 1 with the fox rule off. 6042 positions on the
      // way to the answer where one move loses and another does not, out of 22815
      // searched. The first losing slide of any kind is 0 moves in.
    },
    { id: 4, par: 8,
      rows: ['....aabbd', 'eegg.FhBd', 'iijklChmn', 'oojklppmn', '....qqr..', 'ssttuurvv'],
      // the way through is not the way it looks.
      // par 8, 3 with the fox rule off. 456 positions on the
      // way to the answer where one move loses and another does not, out of 8196
      // searched. The first losing slide of any kind is 2 moves in.
    },
    { id: 5, par: 10,
      rows: ['a.bbdd...', 'a.egg..hi', 'jje.kklhi', '#mmnnolpp', 'qq#rBoFss', '.ttruuCvv'],
      // the route has to be built from the far side.
      // par 10, 2 with the fox rule off. 3245 positions on the
      // way to the answer where one move loses and another does not, out of 12610
      // searched. The first losing slide of any kind is 1 move in.
    },
    { id: 6, par: 11,
      rows: ['.aabBddee', 'ghhbii.j.', 'gk.F.lljm', 'nk.Co.ppm', 'n.qross.t', 'uuqrvvwwt'],
      // his reach is longer than it looks from where he is standing.
      // par 11, 1 with the fox rule off. 17563 positions on the
      // way to the answer where one move loses and another does not, out of 105905
      // searched. The first losing slide of any kind is 0 moves in.
    },
    { id: 7, par: 14,
      rows: ['.aa.bbdde', '.gghhii.e', '.jjBkkllm', 'nnFoo..pm', '..qqCrrps', 'ttuuvvwws'],
      // the long one: ignoring him entirely would take a fraction of the moves.
      // par 14, 2 with the fox rule off. 16106 positions on the
      // way to the answer where one move loses and another does not, out of 52166
      // searched. The first losing slide of any kind is 0 moves in.
    },
    { id: 8, par: 32,
      rows: ['aaC.bF..#', 'ddeebgg.h', 'iijj.Bk.h', '.ll.mmk.n', 'o.ppqqrsn', 'ottuu#rs.'],
      // the wall. Every slide near the middle is one he is waiting for.
      // par 32, 2 with the fox rule off. 47379 positions on the
      // way to the answer where one move loses and another does not, out of 259551
      // searched. The first losing slide of any kind is 0 moves in.
    }
  ];
  return { LEVELS: LEVELS, WORLD: 'woods' };
});
