
/* THE CIRCUS PUZZLES' LADDERS: 22 layouts of each, easy to hard, each found by a search (tools/marble/puz/gencirc*.js)
   and played through by the pilot. Written by tools/marble/puz/mk-circ.js: change the ladders there. */
Object.assign(PLAZAS, {
  CK1: { entry: 2, exit: 2, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+=+-+-+',
    '|. E . k .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CK2: { entry: 2, exit: 1, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+=+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . k .|',
    '+ + + + + +',
    '|. . . . N|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CK3: { entry: 2, exit: 1, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+=+-+-+-+',
    '|. . . W .|',
    '+ + + + + +',
    '|. . . k .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CK4: { entry: 2, exit: 3, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+-+=+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . k .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+ + + + +',
    '|x . . . W|',
    '+-+-+ +-+-+',] },
  CK5: { entry: 2, exit: 2, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|E . . . .|',
    '+ + + + + +',
    '|. . . k .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|x . .|. .|',
    '+-+-+ +-+-+',] },
  CK6: { entry: 2, exit: 1, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+=+-+-+-+',
    '|. . . . W|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|x . . k .|',
    '+ + + +-+ +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CK7: { entry: 2, exit: 1, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+=+-+-+-+',
    '|. . k . W|',
    '+ + + + + +',
    '|. x . . .|',
    '+ + + + + +',
    '|. . . k .|',
    '+-+ + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CK8: { entry: 2, exit: 1, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+=+-+-+-+',
    '|. . . W .|',
    '+ + + + + +',
    '|x . k k .|',
    '+ +-+ + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CK9: { entry: 2, exit: 2, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+=+-+-+',
    '|. . . S .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . k . .|',
    '+ + + + + +',
    '|. . . k .|',
    '+ + + + + +',
    '|. x . . .|',
    '+-+-+ +-+-+',] },
  CK10: { entry: 2, exit: 2, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+=+-+-+',
    '|x . . . .|',
    '+ + + + + +',
    '|. . k|k .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . N .|',
    '+-+-+ +-+-+',] },
  CK11: { entry: 2, exit: 2, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+=+-+-+',
    '|. . . .|.|',
    '+ + + + + +',
    '|. k . k .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|x . . . N|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CK12: { entry: 2, exit: 1, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+=+-+-+-+',
    '|. . . . .|',
    '+ + + +-+ +',
    '|. . k x .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. k . . N|',
    '+-+ + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CK13: { entry: 2, exit: 3, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+-+=+-+',
    '|. . . . S|',
    '+ + + + + +',
    '|. k . . .|',
    '+ + + + + +',
    '|. k . . .|',
    '+ + + + + +',
    '|. . . . x|',
    '+ +-+ + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CK14: { entry: 2, exit: 1, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+=+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . k .|',
    '+ + +-+ + +',
    '|. k . . .|',
    '+ + + + + +',
    '|.|. . . x|',
    '+ + + + + +',
    '|. . . W .|',
    '+-+-+ +-+-+',] },
  CK15: { entry: 2, exit: 2, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+=+-+-+',
    '|.|. . . .|',
    '+ + + + + +',
    '|. k . .|.|',
    '+ + + + + +',
    '|. N . . x|',
    '+ + + + + +',
    '|. k k . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CK16: { entry: 2, exit: 2, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+=+-+-+',
    '|. . . .|.|',
    '+ + + + + +',
    '|. . . k .|',
    '+ + + + + +',
    '|. . W k .|',
    '+ + + + + +',
    '|. k . .|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. x . . .|',
    '+-+-+ +-+-+',] },
  CK17: { entry: 2, exit: 3, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+-+=+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|S . k . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ +-+ + + +',
    '|k . . . .|',
    '+ + + + + +',
    '|. . . k .|',
    '+ + + +-+ +',
    '|. x . . .|',
    '+-+-+ +-+-+',] },
  CK18: { entry: 2, exit: 2, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+=+-+-+',
    '|. . . x .|',
    '+ + + + + +',
    '|. k . . .|',
    '+-+ + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . k k .|',
    '+ + + + + +',
    '|N . . . .|',
    '+-+ + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CK19: { entry: 2, exit: 3, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+-+=+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|.|x . . .|',
    '+ + + + + +',
    '|. k . . .|',
    '+ + + + + +',
    '|.|k . . .|',
    '+ + + +-+ +',
    '|. k . . .|',
    '+ + + + + +',
    '|E . . x .|',
    '+-+-+ +-+-+',] },
  CK20: { entry: 2, exit: 2, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. k .|.|.|',
    '+ + + + + +',
    '|. k . k .|',
    '+ + + + + +',
    '|. . . . x|',
    '+ + + +-+ +',
    '|x . . W .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CK21: { entry: 2, exit: 2, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . k .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + +-+ + +',
    '|. k x .|.|',
    '+ + + + + +',
    '|. . . . x|',
    '+ + + + + +',
    '|. k . W .|',
    '+-+-+ +-+-+',] },
  CK22: { entry: 2, exit: 3, legend: CZ_CAR_L, sp: {kind: 'clowncar'}, map: [
    '+-+-+-+=+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|E . .|. .|',
    '+ + + + + +',
    '|. k . . .|',
    '+ + + + + +',
    '|. k k x .|',
    '+ + + + + +',
    '|. . . . x|',
    '+ + + + +-+',
    '|.|. . . .|',
    '+-+-+ +-+-+',] },
  CP1: { entry: 2, exit: 1, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+=+-+-+-+',
    '|. . o . .|',
    '+ + + + + +',
    '|. . . a .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CP2: { entry: 2, exit: 2, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+=+-+-+',
    '|. o . . .|',
    '+ + + + + +',
    '|. . . a .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CP3: { entry: 2, exit: 3, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+-+=+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . a .|',
    '+ + + + + +',
    '|. o . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CP4: { entry: 2, exit: 3, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+-+=+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . a . .|',
    '+ + + + + +',
    '|. . . . o|',
    '+ + + + + +',
    '|. . . a o|',
    '+-+-+ +-+-+',] },
  CP5: { entry: 2, exit: 3, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+-+=+-+',
    '|. o o . .|',
    '+ + + + + +',
    '|. a . . .|',
    '+ + + + + +',
    '|. a . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CP6: { entry: 2, exit: 1, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+=+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|o o . a .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. a . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CP7: { entry: 2, exit: 1, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+=+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. a a x .|',
    '+ +-+ + + +',
    '|. o . . .|',
    '+ + + + + +',
    '|. o . . .|',
    '+-+-+ +-+-+',] },
  CP8: { entry: 2, exit: 3, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+-+=+-+',
    '|o o . . x|',
    '+ + + + + +',
    '|a . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ +-+ + + +',
    '|. . . a .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CP9: { entry: 2, exit: 3, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+-+=+-+',
    '|. . . .|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. a x a .|',
    '+ + + + + +',
    '|. . . . o|',
    '+ + + + + +',
    '|. . . . o|',
    '+-+-+ +-+-+',] },
  CP10: { entry: 2, exit: 1, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+=+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . a . .|',
    '+ + + + + +',
    '|. a . . .|',
    '+ + + + + +',
    '|. x . o .|',
    '+ +-+ + + +',
    '|. . . o .|',
    '+-+-+ +-+-+',] },
  CP11: { entry: 2, exit: 1, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+=+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . .|. .|',
    '+ + + + + +',
    '|. a a . .|',
    '+ + + + + +',
    '|o o . . .|',
    '+ + + + + +',
    '|o . . a .|',
    '+-+-+ +-+-+',] },
  CP12: { entry: 2, exit: 3, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+-+=+-+',
    '|. . . . o|',
    '+ + + + + +',
    '|. . a o o|',
    '+ +-+ + + +',
    '|. . a . .|',
    '+ + + + + +',
    '|. . . . a|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CP13: { entry: 2, exit: 3, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+-+=+-+',
    '|o o o . .|',
    '+ + + + + +',
    '|. . a . .|',
    '+ + + + + +',
    '|. . a . .|',
    '+ + + + + +',
    '|a . .|. .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CP14: { entry: 2, exit: 3, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+-+=+-+',
    '|o . . . .|',
    '+ + + + + +',
    '|o . . . .|',
    '+ + + + + +',
    '|o . a . .|',
    '+ + + + + +',
    '|a . . a .|',
    '+ + + + + +',
    '|. . .|. .|',
    '+-+-+ +-+-+',] },
  CP15: { entry: 2, exit: 2, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. a a .|a|',
    '+ + + + + +',
    '|. . . .|o|',
    '+ + + + + +',
    '|. . . . o|',
    '+ + + + + +',
    '|. x . . o|',
    '+-+-+ +-+-+',] },
  CP16: { entry: 2, exit: 1, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+=+-+-+-+',
    '|. . x . .|',
    '+ + + + + +',
    '|. . a a .|',
    '+ + + + + +',
    '|o a . . .|',
    '+ + + + + +',
    '|o . . . .|',
    '+ + +-+ + +',
    '|o . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CP17: { entry: 2, exit: 2, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|a . . . x|',
    '+ + + + + +',
    '|. . . a .|',
    '+ + +-+ + +',
    '|o . . a|.|',
    '+ + + + + +',
    '|o . . . .|',
    '+ + + + + +',
    '|o . . . .|',
    '+-+-+ +-+-+',] },
  CP18: { entry: 2, exit: 2, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . a|',
    '+ + + + + +',
    '|. . . x .|',
    '+-+ + + + +',
    '|. a|a . o|',
    '+ + + + + +',
    '|. . . o o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CP19: { entry: 2, exit: 2, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+=+-+-+',
    '|x . . . .|',
    '+ + + + + +',
    '|.|. . a .|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|o o|. . .|',
    '+ + + + + +',
    '|o a . a .|',
    '+ + + + + +',
    '|o . . a .|',
    '+-+-+ +-+-+',] },
  CP20: { entry: 2, exit: 3, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+-+-+=+-+',
    '|. . . . o|',
    '+ + + + + +',
    '|. .|a o o|',
    '+ + + + + +',
    '|. . a a|o|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. a . . .|',
    '+ + + + + +',
    '|. x . . .|',
    '+-+-+ +-+-+',] },
  CP21: { entry: 2, exit: 1, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+=+-+-+-+',
    '|. .|. . .|',
    '+ + + + + +',
    '|x . . . .|',
    '+ + + + + +',
    '|. . a a .|',
    '+ + + + + +',
    '|. o . a .|',
    '+ + + + + +',
    '|o o . . .|',
    '+ + + +-+ +',
    '|o . . a .|',
    '+-+-+ +-+-+',] },
  CP22: { entry: 2, exit: 1, legend: CZ_PYR_L, sp: {kind: 'pyramid'}, map: [
    '+-+=+-+-+-+',
    '|. . . . .|',
    '+ + + +-+ +',
    '|. a . a .|',
    '+ + + + + +',
    '|o a . a .|',
    '+ + + + + +',
    '|o|. . . .|',
    '+ + + + + +',
    '|o o . x .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS1: { entry: 2, exit: 3, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'l3'}, map: [
    '+-+-+-+=+-+',
    '|. . . . 6|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. 3 . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS2: { entry: 2, exit: 1, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'r3'}, map: [
    '+-+=+-+-+-+',
    '|. . . . 1|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. . . 3 .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS3: { entry: 2, exit: 2, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'r3'}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. . . 3 .|',
    '+ + + + + +',
    '|5 . . . .|',
    '+-+-+ +-+-+',] },
  CS4: { entry: 2, exit: 3, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'r4'}, map: [
    '+-+-+-+=+-+',
    '|. . 6 . .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. . . 4 .|',
    '+ + + + + +',
    '|1 . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS5: { entry: 2, exit: 3, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'l4'}, map: [
    '+-+-+-+=+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|4 4 . . .|',
    '+ + + + + +',
    '|1 . . . .|',
    '+-+-+ +-+-+',] },
  CS6: { entry: 2, exit: 1, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'r4'}, map: [
    '+-+=+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|2 . . 1 .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. . . 2 .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS7: { entry: 2, exit: 1, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'l5'}, map: [
    '+-+=+-+-+-+',
    '|. . .|. .|',
    '+ + + + + +',
    '|. 2 . . .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. 6 . 1 .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS8: { entry: 2, exit: 3, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'l5'}, map: [
    '+-+-+-+=+-+',
    '|. . . . .|',
    '+ + +-+ + +',
    '|. . 6 1 .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|3 . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS9: { entry: 2, exit: 1, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'r5'}, map: [
    '+-+=+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. 1 1 . .|',
    '+ + + + + +',
    '|.|. . 6 .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS10: { entry: 2, exit: 2, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'r5'}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . 1 . .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. . .|6 .|',
    '+ + + + + +',
    '|. . . . 3|',
    '+-+-+ +-+-+',] },
  CS11: { entry: 2, exit: 3, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'r6'}, map: [
    '+-+-+-+=+-+',
    '|.|. . . .|',
    '+ + + + + +',
    '|. 2 . 5 .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. . . 4 5|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS12: { entry: 2, exit: 3, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'r6'}, map: [
    '+-+-+-+=+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. 5 2 4 .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. 5 . . .|',
    '+-+-+ +-+-+',] },
  CS13: { entry: 2, exit: 2, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'l6'}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. 3 . 2 .|',
    '+ + + + + +',
    '|2 . . 5 .|',
    '+ + + + + +',
    '|.|. . . .|',
    '+-+-+ +-+-+',] },
  CS14: { entry: 2, exit: 3, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'l6'}, map: [
    '+-+-+-+=+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. . 3 2 .|',
    '+ + + + + +',
    '|l|l ^ r r|',
    '+ + + + + +',
    '|. 5 . . .|',
    '+ + + + + +',
    '|2 . . . .|',
    '+-+-+ +-+-+',] },
  CS15: { entry: 2, exit: 1, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'r7'}, map: [
    '+-+=+-+-+-+',
    '|. . 5 . .|',
    '+ + + + + +',
    '|4 . 5 4 .|',
    '+ + + + + +',
    '|. . . . 1|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS16: { entry: 2, exit: 1, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'r7'}, map: [
    '+-+=+-+-+-+',
    '|. . 3 . .|',
    '+ + + + + +',
    '|l l ^|r r|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + +-+',
    '|. 6 6 5 .|',
    '+ + + + + +',
    '|. . . . 3|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS17: { entry: 2, exit: 2, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'l7'}, map: [
    '+-+-+=+-+-+',
    '|. 5 . . .|',
    '+ + + + + +',
    '|. 4 . . .|',
    '+ + + + + +',
    '|l l|^ r r|',
    '+ + + + + +',
    '|. . 4 . .|',
    '+ + + + + +',
    '|. 5 . 1 .|',
    '+-+ + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS18: { entry: 2, exit: 3, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'r7'}, map: [
    '+-+-+-+=+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. 5 . . .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+-+ + + + +',
    '|. . 6 6 .|',
    '+ + + + + +',
    '|. . . 3 .|',
    '+ + + +-+ +',
    '|. . . . 3|',
    '+-+-+ +-+-+',] },
  CS19: { entry: 2, exit: 1, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'l8'}, map: [
    '+-+=+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. 2 1 2|.|',
    '+ + + + + +',
    '|. . 5 . .|',
    '+-+ + + + +',
    '|. . . . 4|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS20: { entry: 2, exit: 3, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'l8'}, map: [
    '+-+-+-+=+-+',
    '|. . 5 . .|',
    '+ + + + + +',
    '|. . 5 . .|',
    '+ + + + + +',
    '|. . 4 6 .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. 6 .|. .|',
    '+ + + + + +',
    '|. . .|. .|',
    '+-+-+ +-+-+',] },
  CS21: { entry: 2, exit: 2, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'r8'}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + +-+',
    '|. . 5 4 .|',
    '+ + + + +-+',
    '|. . 1 . 2|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + + + + +',
    '|. . . 2 .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CS22: { entry: 2, exit: 1, legend: CZ_SCL_L, sp: {kind: 'scales', anvil: 'l8'}, map: [
    '+-+=+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. 4 1 . .|',
    '+ + + + + +',
    '|l l ^ r r|',
    '+ + +-+ + +',
    '|2 5|. . 2|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CH1: { entry: 2, exit: 0, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 3, swapT: 0.95, rounds: 1, pairs: 0, seed: 8287}, map: [
    '+=+-+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. t t t .|',
    '+ + + + + +',
    '|.|p|p|p|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CH2: { entry: 2, exit: 0, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 4, swapT: 0.92, rounds: 1, pairs: 0, seed: 1895}, map: [
    '+=+-+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. t t t .|',
    '+ + + + + +',
    '|.|p|p|p|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CH3: { entry: 2, exit: 2, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 5, swapT: 0.9, rounds: 1, pairs: 0, seed: 4795}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. t t t .|',
    '+ + + + + +',
    '|.|p|p|p|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CH4: { entry: 2, exit: 0, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 6, swapT: 0.87, rounds: 1, pairs: 0, seed: 6769}, map: [
    '+=+-+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. t t t .|',
    '+ + + + + +',
    '|.|p|p|p|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CH5: { entry: 2, exit: 2, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 3, swapT: 0.85, rounds: 2, pairs: 0, seed: 4886}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. t t t .|',
    '+ + + + + +',
    '|.|p|p|p|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CH6: { entry: 2, exit: 2, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 4, swapT: 0.82, rounds: 2, pairs: 0, seed: 5724}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. t t t .|',
    '+ + + + + +',
    '|.|p|p|p|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CH7: { entry: 2, exit: 2, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 4, swapT: 0.79, rounds: 2, pairs: 0, seed: 2179}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. t t t .|',
    '+ + + + + +',
    '|.|p|p|p|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CH8: { entry: 2, exit: 4, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 5, swapT: 0.77, rounds: 2, pairs: 0, seed: 6372}, map: [
    '+-+-+-+-+=+',
    '|. . . . .|',
    '+ + + + + +',
    '|. t t t .|',
    '+ + + + + +',
    '|.|p|p|p|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CH9: { entry: 2, exit: 2, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 5, swapT: 0.74, rounds: 2, pairs: 0, seed: 485}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. t t t .|',
    '+ + + + + +',
    '|.|p|p|p|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CH10: { entry: 2, exit: 2, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 6, swapT: 0.71, rounds: 2, pairs: 0, seed: 4212}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. t t t .|',
    '+ + + + + +',
    '|.|p|p|p|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CH11: { entry: 2, exit: 2, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 5, swapT: 0.69, rounds: 2, pairs: 0, seed: 7267}, map: [
    '+-+-+=+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|. t t t .|',
    '+ + + + + +',
    '|.|p|p|p|.|',
    '+ + + + + +',
    '|. . . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CH12: { entry: 2, exit: 0, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 6, swapT: 0.66, rounds: 2, pairs: 0, seed: 4618}, map: [
    '+=+-+-+-+-+-+',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. t t t t .|',
    '+ + + + + + +',
    '|.|p|p|p|p|.|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+-+-+ +-+-+-+',] },
  CH13: { entry: 2, exit: 2, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 7, swapT: 0.64, rounds: 2, pairs: 0, seed: 6197}, map: [
    '+-+-+=+-+-+-+',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. t t t t .|',
    '+ + + + + + +',
    '|.|p|p|p|p|.|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+-+-+ +-+-+-+',] },
  CH14: { entry: 2, exit: 5, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 4, swapT: 0.61, rounds: 3, pairs: 0, seed: 5197}, map: [
    '+-+-+-+-+-+=+',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. t t t t .|',
    '+ + + + + + +',
    '|.|p|p|p|p|.|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+-+-+ +-+-+-+',] },
  CH15: { entry: 2, exit: 2, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 5, swapT: 0.58, rounds: 3, pairs: 0, seed: 8176}, map: [
    '+-+-+=+-+-+-+',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. t t t t .|',
    '+ + + + + + +',
    '|.|p|p|p|p|.|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+-+-+ +-+-+-+',] },
  CH16: { entry: 2, exit: 5, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 5, swapT: 0.56, rounds: 3, pairs: 0, seed: 3019}, map: [
    '+-+-+-+-+-+=+',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. t t t t .|',
    '+ + + + + + +',
    '|.|p|p|p|p|.|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+-+-+ +-+-+-+',] },
  CH17: { entry: 2, exit: 2, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 6, swapT: 0.53, rounds: 3, pairs: 0, seed: 2991}, map: [
    '+-+-+=+-+-+-+',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. t t t t .|',
    '+ + + + + + +',
    '|.|p|p|p|p|.|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+-+-+ +-+-+-+',] },
  CH18: { entry: 2, exit: 0, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 6, swapT: 0.5, rounds: 3, pairs: 1, seed: 2679}, map: [
    '+=+-+-+-+-+-+',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. t t t t .|',
    '+ + + + + + +',
    '|.|p|p|p|p|.|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+-+-+ +-+-+-+',] },
  CH19: { entry: 2, exit: 5, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 7, swapT: 0.48, rounds: 3, pairs: 1, seed: 2654}, map: [
    '+-+-+-+-+-+=+',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. t t t t .|',
    '+ + + + + + +',
    '|.|p|p|p|p|.|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+-+-+ +-+-+-+',] },
  CH20: { entry: 2, exit: 2, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 8, swapT: 0.45, rounds: 3, pairs: 1, seed: 5017}, map: [
    '+-+-+=+-+-+-+',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. t t t t .|',
    '+ + + + + + +',
    '|.|p|p|p|p|.|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+-+-+ +-+-+-+',] },
  CH21: { entry: 2, exit: 2, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 9, swapT: 0.43, rounds: 3, pairs: 1, seed: 7901}, map: [
    '+-+-+=+-+-+-+',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. t t t t .|',
    '+ + + + + + +',
    '|.|p|p|p|p|.|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+-+-+ +-+-+-+',] },
  CH22: { entry: 2, exit: 0, legend: CZ_SHL_L, sp: {kind: 'shells', swaps: 10, swapT: 0.4, rounds: 3, pairs: 1, seed: 2462}, map: [
    '+=+-+-+-+-+-+',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. t t t t .|',
    '+ + + + + + +',
    '|.|p|p|p|p|.|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+ + + + + + +',
    '|. . . . . .|',
    '+-+-+ +-+-+-+',] },
  CN1: { entry: 2, exit: 3, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.42, hold: 1.8, side: 'e', seed: 7153}, map: [
    '+-+-+-+=+-+',
    '|o . . . o|',
    '+ + + + + +',
    '|o . o o o|',
    '+ + + + + +',
    '|o . o o o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN2: { entry: 2, exit: 1, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.41, hold: 1.8, side: 'e', seed: 8049}, map: [
    '+-+=+-+-+-+',
    '|o . o o o|',
    '+ + + + + +',
    '|o . o o o|',
    '+ + + + + +',
    '|. . o o o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN3: { entry: 2, exit: 0, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.4, hold: 1.7, side: 'e', seed: 2806}, map: [
    '+=+-+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|o o o o .|',
    '+ + + + + +',
    '|o o o . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN4: { entry: 2, exit: 3, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.39, hold: 1.7, side: 'e', seed: 86}, map: [
    '+-+-+-+=+-+',
    '|. . . . o|',
    '+ + + + + +',
    '|. o o o o|',
    '+ + + + + +',
    '|. . o o o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN5: { entry: 2, exit: 3, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.38, hold: 1.6, side: 'w', seed: 3133}, map: [
    '+-+-+-+=+-+',
    '|o o o . .|',
    '+ + + + + +',
    '|o o . o .|',
    '+ + + + + +',
    '|o o . . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN6: { entry: 2, exit: 2, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.37, hold: 1.6, side: 'w', seed: 6404}, map: [
    '+-+-+=+-+-+',
    '|o . . . .|',
    '+ + + + + +',
    '|o o o o .|',
    '+ + + + + +',
    '|o o . . .|',
    '+ + + + + +',
    '|o o . o o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN7: { entry: 2, exit: 1, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.36, hold: 1.5, side: 'w', seed: 7826}, map: [
    '+-+=+-+-+-+',
    '|o . . . .|',
    '+ + + + + +',
    '|o o o o .|',
    '+ + + + + +',
    '|o o o . .|',
    '+ + + + + +',
    '|. o o . o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN8: { entry: 2, exit: 0, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.35, hold: 1.5, side: 'w', seed: 8734}, map: [
    '+=+-+-+-+-+',
    '|. . . . .|',
    '+ + + + + +',
    '|o . o o .|',
    '+ + + + + +',
    '|o o o . .|',
    '+ + + + + +',
    '|o o o . o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN9: { entry: 2, exit: 0, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.34, hold: 1.4, side: 'e', seed: 4812}, map: [
    '+=+-+-+-+-+',
    '|. o o o o|',
    '+ + + + + +',
    '|. . . o o|',
    '+ + + + + +',
    '|. o . . o|',
    '+ + + + + +',
    '|o o o . o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN10: { entry: 2, exit: 2, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.33, hold: 1.4, side: 'e', seed: 3976}, map: [
    '+-+-+=+-+-+',
    '|o o . . .|',
    '+ + + + + +',
    '|o o o o .|',
    '+ + + + + +',
    '|. o . . .|',
    '+ + + + + +',
    '|. . . o o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN11: { entry: 2, exit: 1, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.32, hold: 1.3, side: 'w', seed: 3792}, map: [
    '+-+=+-+-+-+',
    '|o . . o o|',
    '+ + + + + +',
    '|o o . . o|',
    '+ + + + + +',
    '|o o o . .|',
    '+ + + + + +',
    '|o o . . o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN12: { entry: 2, exit: 3, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.3, hold: 1.3, side: 'e', seed: 6874}, map: [
    '+-+-+-+=+-+',
    '|o o o . o|',
    '+ + + + + +',
    '|o o o . o|',
    '+ + + + + +',
    '|o . . . o|',
    '+ + + + + +',
    '|o . o o o|',
    '+ + + + + +',
    '|o . . o .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN13: { entry: 2, exit: 4, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.29, hold: 1.2, side: 'e', seed: 8703}, map: [
    '+-+-+-+-+=+',
    '|o o o o .|',
    '+ + + + + +',
    '|o o . . .|',
    '+ + + + + +',
    '|o . . o o|',
    '+ + + + + +',
    '|. . o o o|',
    '+ + + + + +',
    '|. o . o .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN14: { entry: 2, exit: 1, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.28, hold: 1.2, side: 'e', seed: 1421}, map: [
    '+-+=+-+-+-+',
    '|o . o . o|',
    '+ + + + + +',
    '|o . . . .|',
    '+ + + + + +',
    '|o . o o .|',
    '+ + + + + +',
    '|o o o . .|',
    '+ + + + + +',
    '|o . . . o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN15: { entry: 2, exit: 4, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.27, hold: 1.1, side: 'e', seed: 803}, map: [
    '+-+-+-+-+=+',
    '|. o . . .|',
    '+ + + + + +',
    '|. . . o o|',
    '+ + + + + +',
    '|. o o . o|',
    '+ + + + + +',
    '|. . . . o|',
    '+ + + + + +',
    '|o o o . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN16: { entry: 2, exit: 1, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.26, hold: 1.1, side: 'e', seed: 4235}, map: [
    '+-+=+-+-+-+',
    '|o . . o o|',
    '+ + + + + +',
    '|. . o o o|',
    '+ + + + + +',
    '|. o o o o|',
    '+ + + + + +',
    '|. . o . o|',
    '+ + + + + +',
    '|o . . . o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN17: { entry: 2, exit: 0, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.25, hold: 1, side: 'e', seed: 6563}, map: [
    '+=+-+-+-+-+',
    '|. o o o o|',
    '+ + + + + +',
    '|. . . o o|',
    '+ + + + + +',
    '|. o . . .|',
    '+ + + + + +',
    '|o o . o .|',
    '+ + + + + +',
    '|o o o . .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN18: { entry: 2, exit: 2, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.24, hold: 1, side: 'w', seed: 4810}, map: [
    '+-+-+=+-+-+',
    '|o . . . .|',
    '+ + + + + +',
    '|o o o o .|',
    '+ + + + + +',
    '|o o o . .|',
    '+ + + + + +',
    '|o o . . o|',
    '+ + + + + +',
    '|. . . o o|',
    '+ + + + + +',
    '|o . o o o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN19: { entry: 2, exit: 1, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.23, hold: 0.9, side: 'w', seed: 350}, map: [
    '+-+=+-+-+-+',
    '|o . . o o|',
    '+ + + + + +',
    '|o o . o o|',
    '+ + + + + +',
    '|o . . . o|',
    '+ + + + + +',
    '|. . o o o|',
    '+ + + + + +',
    '|. o o . o|',
    '+ + + + + +',
    '|. . . . o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN20: { entry: 2, exit: 1, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.22, hold: 0.9, side: 'w', seed: 6413}, map: [
    '+-+=+-+-+-+',
    '|o . . o o|',
    '+ + + + + +',
    '|o o . . o|',
    '+ + + + + +',
    '|o o o . .|',
    '+ + + + + +',
    '|o . . . o|',
    '+ + + + + +',
    '|o . o . o|',
    '+ + + + + +',
    '|. . o o o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN21: { entry: 2, exit: 4, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.21, hold: 0.8, side: 'w', seed: 4963}, map: [
    '+-+-+-+-+=+',
    '|o o o . .|',
    '+ + + + + +',
    '|o o . . o|',
    '+ + + + + +',
    '|. . . o o|',
    '+ + + + + +',
    '|o . o o o|',
    '+ + + + + +',
    '|o . . . o|',
    '+ + + + + +',
    '|. o o . o|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
  CN22: { entry: 2, exit: 4, legend: CZ_KNF_L, sp: {kind: 'knives', throwT: 0.2, hold: 0.8, side: 'e', seed: 1080}, map: [
    '+-+-+-+-+=+',
    '|o o o o .|',
    '+ + + + + +',
    '|o o . . .|',
    '+ + + + + +',
    '|o . . o .|',
    '+ + + + + +',
    '|. . o o o|',
    '+ + + + + +',
    '|. o o o o|',
    '+ + + + + +',
    '|. . . o .|',
    '+ + + + + +',
    '|. . . . .|',
    '+-+-+ +-+-+',] },
});
Object.assign(TRY_COURSES, {"clowncar":["CK1","CK11","CK22"],"lck0":["CK1","CK2","CK3","CK4","CK5","CK6","CK7"],"lck1":["CK8","CK9","CK10","CK11","CK12","CK13","CK14","CK15"],"lck2":["CK16","CK17","CK18","CK19","CK20","CK21","CK22"],"pyramid":["CP1","CP11","CP22"],"lcp0":["CP1","CP2","CP3","CP4","CP5","CP6","CP7"],"lcp1":["CP8","CP9","CP10","CP11","CP12","CP13","CP14","CP15"],"lcp2":["CP16","CP17","CP18","CP19","CP20","CP21","CP22"],"scales":["CS1","CS11","CS22"],"lcs0":["CS1","CS2","CS3","CS4","CS5","CS6","CS7"],"lcs1":["CS8","CS9","CS10","CS11","CS12","CS13","CS14","CS15"],"lcs2":["CS16","CS17","CS18","CS19","CS20","CS21","CS22"],"shells":["CH1","CH11","CH22"],"lch0":["CH1","CH2","CH3","CH4","CH5","CH6","CH7"],"lch1":["CH8","CH9","CH10","CH11","CH12","CH13","CH14","CH15"],"lch2":["CH16","CH17","CH18","CH19","CH20","CH21","CH22"],"knifethrower":["CN1","CN11","CN22"],"lcn0":["CN1","CN2","CN3","CN4","CN5","CN6","CN7"],"lcn1":["CN8","CN9","CN10","CN11","CN12","CN13","CN14","CN15"],"lcn2":["CN16","CN17","CN18","CN19","CN20","CN21","CN22"],"cpuzzles":["CK11","CP11","CS11","CH11","CN11"]});
CZ_TRY.push(...["clowncar","lck0","lck1","lck2","pyramid","lcp0","lcp1","lcp2","scales","lcs0","lcs1","lcs2","shells","lch0","lch1","lch2","knifethrower","lcn0","lcn1","lcn2","cpuzzles"]);
Object.assign(TRY_TITLES, {"clowncar":"THE CLOWN CAR","lck0":"THE CLOWN CAR 1-7","lck1":"THE CLOWN CAR 8-15","lck2":"THE CLOWN CAR 16-22","pyramid":"THE ACROBAT PYRAMID","lcp0":"THE ACROBAT PYRAMID 1-7","lcp1":"THE ACROBAT PYRAMID 8-15","lcp2":"THE ACROBAT PYRAMID 16-22","scales":"THE BALANCE SCALES","lcs0":"THE BALANCE SCALES 1-7","lcs1":"THE BALANCE SCALES 8-15","lcs2":"THE BALANCE SCALES 16-22","shells":"THE SHELL GAME","lch0":"THE SHELL GAME 1-7","lch1":"THE SHELL GAME 8-15","lch2":"THE SHELL GAME 16-22","knifethrower":"THE KNIFE THROWER","lcn0":"THE KNIFE THROWER 1-7","lcn1":"THE KNIFE THROWER 8-15","lcn2":"THE KNIFE THROWER 16-22","cpuzzles":"CIRCUS PUZZLES"});
Object.assign(TRY_NEWS, {"clowncar":"Push the clowns into the little car. They get in only through its back door. Three squares, easy to hard","pyramid":"Push the acrobats onto the gold stars, and they climb into a pyramid. Three squares, easy to hard","scales":"Push weights onto the two pans until the scale hangs level. Three squares, easy to hard","shells":"Watch the cup with the gold star as the magician shuffles, then roll onto its pad. Three squares, easy to hard","knifethrower":"Watch where the knives land. Then cross on the boards he did not hit. Three squares, easy to hard","cpuzzles":"The circus puzzles, one after another"});
Object.assign(PLAZA_NEWS, {"CK1":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK2":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK3":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK4":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK5":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK6":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK7":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK8":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK9":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK10":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK11":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK12":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK13":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK14":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK15":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK16":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK17":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK18":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK19":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK20":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK21":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CK22":"Push every clown into the car. They get in only through its back door, where the white arrows point in","CP1":"Push an acrobat onto every gold star. The pad by the road puts them back","CP2":"Push an acrobat onto every gold star. The pad by the road puts them back","CP3":"Push an acrobat onto every gold star. The pad by the road puts them back","CP4":"Push an acrobat onto every gold star. The pad by the road puts them back","CP5":"Push an acrobat onto every gold star. The pad by the road puts them back","CP6":"Push an acrobat onto every gold star. The pad by the road puts them back","CP7":"Push an acrobat onto every gold star. The pad by the road puts them back","CP8":"Push an acrobat onto every gold star. The pad by the road puts them back","CP9":"Push an acrobat onto every gold star. The pad by the road puts them back","CP10":"Push an acrobat onto every gold star. The pad by the road puts them back","CP11":"Push an acrobat onto every gold star. The pad by the road puts them back","CP12":"Push an acrobat onto every gold star. The pad by the road puts them back","CP13":"Push an acrobat onto every gold star. The pad by the road puts them back","CP14":"Push an acrobat onto every gold star. The pad by the road puts them back","CP15":"Push an acrobat onto every gold star. The pad by the road puts them back","CP16":"Push an acrobat onto every gold star. The pad by the road puts them back","CP17":"Push an acrobat onto every gold star. The pad by the road puts them back","CP18":"Push an acrobat onto every gold star. The pad by the road puts them back","CP19":"Push an acrobat onto every gold star. The pad by the road puts them back","CP20":"Push an acrobat onto every gold star. The pad by the road puts them back","CP21":"Push an acrobat onto every gold star. The pad by the road puts them back","CP22":"Push an acrobat onto every gold star. The pad by the road puts them back","CS1":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS2":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS3":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS4":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS5":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS6":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS7":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS8":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS9":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS10":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS11":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS12":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS13":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS14":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS15":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS16":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS17":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS18":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS19":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS20":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS21":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CS22":"Level the scale: the same kilos on each pan. The boards over the pans add them up","CH1":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH2":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH3":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH4":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH5":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH6":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH7":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH8":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH9":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH10":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH11":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH12":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH13":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH14":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH15":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH16":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH17":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH18":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH19":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH20":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH21":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CH22":"Keep your eye on the cup with the star. When the pads light, roll onto the pad in front of it. The wrong cup sends you back","CN1":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN2":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN3":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN4":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN5":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN6":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN7":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN8":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN9":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN10":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN11":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN12":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN13":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN14":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN15":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN16":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN17":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN18":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN19":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN20":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN21":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again","CN22":"Remember the boards he hits. Cross on the others: a knife sends you back, and he throws again"});
